sudo: false # faster builds

cache:
  directories:
    - '$HOME/.m2/repository'

addons:
  sonarcloud:
    organization: 'weather-service'

language: java

jdk:
  - oraclejdk8

install:
  - 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'

script:
  - 'mvn verify'
  - 'mvn clean cobertura:cobertura coveralls:report'

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
